### ISSUE TITLE
Characters cannot jump while on a button

### ISSUE THREAD

**Issue by erikajoun** [GameDevStudioUCSD/Shadowlight#22]
Characters cannot jump while on the button or pressure plate because IsGrounded() checks for the ground using raycasts, but these objects are set to the Ignore Raycasts layer to prevent creating shadows.

**Comment by shabbyowen** [comment]
How about making default layer the "Ignore Raycasts" layer ?
Or we can set layers for all walls&floors and decorations to "Ignore Raycasts" layer and feed in Raycast Mask when calling RaycastAll?
