### ISSUE TITLE
Improve Jump

### ISSUE THREAD

**Issue by eminguyen** [GameDevStudioUCSD/Shadowlight#33]
Re add fall force to make jump feel less "floaty".

**Comment by sru** [comment]
There might be a way to do this without adding the "fall force." I initially removed it because it was bugging out the animation (basically, the y velocity kept going negative even though the character was on the ground and not falling).

**Comment by griffithsdanielc** [comment]
Are we sure this is still necessary? I already messed with the jump force, masses, and gravity scale to make you jump the same height but fall down faster.
