### ISSUE TITLE
Player on top of the box doesn't move with the box

### ISSUE THREAD

**Issue by erikajoun** [GameDevStudioUCSD/Shadowlight#46]

**Comment by griffithsdanielc** [comment]
For a player to stick to the top of the box, they need to have some friction. But if we make their friction nonzero, they also stick to walls and slide down too slowly. In particular, when Shadow shoves a box and jumps, he'll continually stick to the side of the box as it moves and "float".
We need to make the player stick to the box from the top, but not the sides, and not to the walls.
